CFLAGS = -mmic -O3 -ipo -std=gnu99 -DSIZE=4096

all: lap_intel lap_omni lap_abt

lap_intel: lap_omp.c
	icc -openmp ${CFLAGS} -o $@ lap_omp.c

lap_omni: lap_omp.c
	ompcc ${CFLAGS} -o $@ lap_omp.c

lap_abt: lap_omp.c
	${HOME}/inst/omni-compiler_argobots/bin/ompcc ${CFLAGS} -o $@ lap_omp.c \
	    -Wl,-dn,-labt,-dy -L${HOME}/inst/argobots/lib
